### ISSUE TITLE
Integration test errors

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#178]
The integration tests are still throwing errors for me on the `develop` branch. Let me know if it's a configuration error on my end.

```
 FAIL  tests/index.test.ts (354.493s)
  testnet
    contract deployment
      ✓ should define zkopru address (14ms)
    1: Zk Account
      ✓ alice should have 100 ETH for her initial balance (12ms)
      ✓ bob should have 100 ETH for his initial balance (189ms)
      ✓ carl should have 100 ETH for his initial balance (900ms)
    2: Register verifying keys
      ✓ coordinator can register vks (14492ms)
      ✓ alice, bob, and carl cannot register vks (1128ms)
    3: Complete setup
      3-1: before completeSetup() called
        ✓ should allow only the coordinator (1530ms)
      3-2: after completeSetup() called
        ✓ should reject every register txs (83ms)
      3-3: coordinator can register ERC20 or ERC721 tokens.
        ✓ should register sample erc20 and erc721 (415ms)
    4: Deposits
      4-1: users deposit assets
        ✓ ether: Alice, Bob, and Carl each deposit 10 ETH (2997ms)
        ✓ erc20: Bob deposits ERC20 (1507ms)
        ✓ erc721: Carl deposits NFTs (1598ms)
      4-2: coordinator commits MassDeposit
        ✓ coordinator should have 5 pending deposits (1175ms)
    5: Coordinator create the first block
      register coordinator account
        ✓ should register "coordinator" account (338ms)
      coordinator creates the first block when the aggregated fee is enough
        ✓ should propose a new block within a few seconds (1067ms)
        ✕ should process the new submitted block (26320ms)
      new block should update trees
        ✕ should increase utxo index to at least 32(sub tree size) (3ms)
        ✕ should update the utxo root (1ms)
      users subscribe Proposal() events
        ✕ wallets should have updated processed block number (5002ms)
    6: Zk Transactions round 1
      users send zk txs to the coordinator
        ✓ create 3 transactions: alice transfer 1 Ether to Bob. Bob transfer 1 ERC20 to Carl, and Carl transfer 1 nft to Alice (16814ms)
        ✓ they should send zk transactions to the coordinator (1087ms)
        ✕ coordinator should propose a new block and wallet clients subscribe them (3951ms)
        ✕ wallets should have new spendable utxos as they sync the new block (10ms)
    7: Zk Transactions round 2
      users withdraw their assets from the layer 2
        ✕ create 3 transactions: alice withdraw 1 NFT. Bob withdraw 1 ETH, and Carl withdraw 1 ERC20 (12ms)
        ✕ they should send zk transactions to the coordinator (1ms)
        ✓ coordinator should propose a new block and wallet clients subscribe them (84112ms)
        ✕ wallets should have new spendable utxos as they sync the new block (16ms)
    8: Instant withdrawal
      alice, bob, and carl has unfinalized withdrawable notes
        ✕ alice has 1 unfinalized withdrawable note (8ms)
        ✕ bob has 1 unfinalized withdrawable note (3ms)
        ✕ carl has 1 unfinalized withdrawable note (4ms)
      coordinator prepays ETH for Bob
        ✕ should transfer 1 ETH to Bob (5ms)
    9: Zk Transactions round 3
      users send zk txs to the coordinator
        ✓ create 3 transactions: alice transfer 1 Ether to Bob. Bob transfer 1 Ether to Carl, and Carl transfer 1 Ether to Alice (12017ms)
        ✓ they should send zk transactions to the coordinator & coordinator creates an invalid block (317ms)
        ✓ coordinator proposes an invalid block and gets slashed (143849ms)
    10: Migration
      ✎ todo please add test scenarios here

  ● testnet › 5: Coordinator create the first block › coordinator creates the first block when the aggregated fee is enough › should process the new submitted block

    expect(received).toStrictEqual(expected) // deep equality

    Expected: 1
    Received: 0



      at tests/cases/5_create_block.ts:1583:31
      at fulfilled (tests/cases/5_create_block.ts:1407:24)

  ● testnet › 5: Coordinator create the first block › new block should update trees › should increase utxo index to at least 32(sub tree size)

    expect(received).toStrictEqual(expected) // deep equality

    Expected: "0"
    Received: "32"

      163 |         expect(
      164 |           prevGroveSnapshot.utxoTreeIndex.addn(32).toString(),
    > 165 |         ).toStrictEqual(newGroveSnapshot.utxoTreeIndex.toString())
          |           ^
      166 |       })
      167 |       it('should update the utxo root', () => {
      168 |         expect(prevGroveSnapshot.utxoTreeRoot.toString()).not.toStrictEqual(

      at Object.<anonymous> (tests/index.test.ts:165:11)
          at runMicrotasks (<anonymous>)

  ● testnet › 5: Coordinator create the first block › new block should update trees › should update the utxo root

    expect(received).not.toStrictEqual(expected) // deep equality

    Expected: not "3092784425575682849215806387188191163008086618667633588848126820278484295451"

      166 |       })
      167 |       it('should update the utxo root', () => {
    > 168 |         expect(prevGroveSnapshot.utxoTreeRoot.toString()).not.toStrictEqual(
          |                                                               ^
      169 |           newGroveSnapshot.utxoTreeRoot.toString(),
      170 |         )
      171 |       })

      at Object.<anonymous> (tests/index.test.ts:168:63)
          at runMicrotasks (<anonymous>)

  ● testnet › 5: Coordinator create the first block › users subscribe Proposal() events › wallets should have updated processed block number

    expect(received).toStrictEqual(expected) // deep equality

    Expected: 1
    Received: undefined



      at tests/cases/5_create_block.ts:1653:62
      at fulfilled (tests/cases/5_create_block.ts:1407:24)

  ● testnet › 6: Zk Transactions round 1 › users send zk txs to the coordinator › coordinator should propose a new block and wallet clients subscribe them

    expect(received).toHaveLength(expected)

    Expected length: 3
    Received length: 0
    Received array:  []



      at tests/cases/6_zk_tx_round_1.ts:2715:53
      at fulfilled (tests/cases/6_zk_tx_round_1.ts:2278:24)
          at runMicrotasks (<anonymous>)

  ● testnet › 6: Zk Transactions round 1 › users send zk txs to the coordinator › wallets should have new spendable utxos as they sync the new block

    TypeError: Cannot read property 'find' of undefined



      at tests/cases/6_zk_tx_round_1.ts:2752:57
      at fulfilled (tests/cases/6_zk_tx_round_1.ts:2278:24)
          at runMicrotasks (<anonymous>)

  ● testnet › 7: Zk Transactions round 2 › users withdraw their assets from the layer 2 › create 3 transactions: alice withdraw 1 NFT. Bob withdraw 1 ETH, and Carl withdraw 1 ERC20

    Not enough Ether. Insufficient: 0.0574

      13 | import { RawTx } from './raw-tx'
      14 |
    > 15 | export class TxBuilder {
         | ^
      16 |   spendables: Utxo[]
      17 |
      18 |   sendings: Outflow[]

      at TxBuilder.build (../transaction/src/tx-builder.ts:15:1)
      at tests/cases/7_zk_tx_round_2.ts:2325:8
      at fulfilled (tests/cases/7_zk_tx_round_2.ts:2209:24)
          at runMicrotasks (<anonymous>)

  ● testnet › 7: Zk Transactions round 2 › users withdraw their assets from the layer 2 › they should send zk transactions to the coordinator

    TypeError: Cannot read property 'encode' of undefined

      557 |                             .nft()
      558 |                             .toUint256()
    > 559 |                             .toString(),
          |                    ^
      560 |                         to: outflow.publicData.to.toAddress().toString(),
      561 |                         fee: outflow.publicData.fee.toAddress().toString(),
      562 |                         status: transaction_1.UtxoStatus.NON_INCLUDED,

      at ZkWallet.<anonymous> (../zk-wizard/dist/zk-wallet.js:559:20)
      at ../zk-wizard/src/zk-wallet.ts:85:25
      at Object.<anonymous>.__awaiter (../zk-wizard/dist/zk-wallet.js:10:10)
      at ZkWallet.sendLayer2Tx (../zk-wizard/dist/zk-wallet.js:556:12)
      at tests/cases/7_zk_tx_round_2.ts:2528:65
      at tests/cases/7_zk_tx_round_2.ts:2250:38
      at Object.<anonymous>.__awaiter (tests/cases/7_zk_tx_round_2.ts:2193:10)
      at Object.<anonymous> (tests/cases/7_zk_tx_round_2.ts:2511:12)

  ● testnet › 7: Zk Transactions round 2 › users withdraw their assets from the layer 2 › wallets should have new spendable utxos as they sync the new block

    expect(received).toBeUndefined()

    Received: ["0x01"]



      at tests/cases/7_zk_tx_round_2.ts:2677:58
      at fulfilled (tests/cases/7_zk_tx_round_2.ts:2209:24)
          at runMicrotasks (<anonymous>)

  ● testnet › 8: Instant withdrawal › alice, bob, and carl has unfinalized withdrawable notes › alice has 1 unfinalized withdrawable note

    expect(received).toHaveLength(expected)

    Expected length: 1
    Received length: 0
    Received array:  []



      at tests/cases/8_instant_withdrawals.ts:1372:104
      at fulfilled (tests/cases/8_instant_withdrawals.ts:1283:24)
          at runMicrotasks (<anonymous>)

  ● testnet › 8: Instant withdrawal › alice, bob, and carl has unfinalized withdrawable notes › bob has 1 unfinalized withdrawable note

    expect(received).toHaveLength(expected)

    Expected length: 1
    Received length: 0
    Received array:  []



      at tests/cases/8_instant_withdrawals.ts:1405:100
      at fulfilled (tests/cases/8_instant_withdrawals.ts:1283:24)
          at runMicrotasks (<anonymous>)

  ● testnet › 8: Instant withdrawal › alice, bob, and carl has unfinalized withdrawable notes › carl has 1 unfinalized withdrawable note

    expect(received).toHaveLength(expected)

    Expected length: 1
    Received length: 0
    Received array:  []



      at tests/cases/8_instant_withdrawals.ts:1438:102
      at fulfilled (tests/cases/8_instant_withdrawals.ts:1283:24)
          at runMicrotasks (<anonymous>)

  ● testnet › 8: Instant withdrawal › coordinator prepays ETH for Bob › should transfer 1 ETH to Bob

    expect(received).toHaveLength(expected)

    Expected length: 1
    Received length: 0
    Received array:  []



      at tests/cases/8_instant_withdrawals.ts:1469:27
      at fulfilled (tests/cases/8_instant_withdrawals.ts:1283:24)
          at runMicrotasks (<anonymous>)

--------------------------|----------|----------|----------|----------|-------------------|
File                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------|----------|----------|----------|----------|-------------------|
All files                 |    90.57 |    85.71 |    93.33 |    90.04 |                   |
 1_create_accounts.ts     |      100 |      100 |      100 |      100 |                   |
 2_register_vks.ts        |      100 |      100 |      100 |      100 |                   |
 3_complete_setup.ts      |    98.59 |    85.71 |      100 |      100 |               117 |
 4_deposit.ts             |      100 |      100 |      100 |      100 |                   |
 5_create_block.ts        |    94.74 |    81.82 |      100 |    96.88 |                49 |
 6_zk_tx_round_1.ts       |    96.74 |       90 |    95.24 |    96.59 |       176,178,181 |
 7_zk_tx_round_2.ts       |    54.55 |       90 |       55 |    52.38 |... 41,142,180,181 |
 8_instant_withdrawals.ts |       75 |      100 |      100 |    67.86 |... 48,54,55,56,57 |
 9_zk_tx_round_3.ts       |      100 |      100 |      100 |      100 |                   |
 context.ts               |    99.03 |       50 |      100 |      100 |               140 |
--------------------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       13 failed, 1 todo, 21 passed, 35 total
Snapshots:   0 total
```

**Comment by wanseob** [comment]
I've pushed a new commit to fix them would you please check them? I feel current docker based integration system has so many errors. Strongly feel that we need to refactor the system. It's lagging dev progress now :( sorry for the inconvenience. My next task should be refactoring them with hardhat framework.

**Comment by JChanceHud** [comment]
@wanseob I noticed the `pullOrBuildAndGetContainer` was replaced with `buildAndGetContainer` in the integration test context. I think it makes sense to switch back to the pull or build logic so that local versions of the image can be used, otherwise it's rebuilt from scratch each time.

**Comment by wanseob** [comment]
@JChanceHud ah okay just a moment please, let me push the images first and then change that function

**Comment by wanseob** [comment]
@JChanceHud pushed new 2 commits to the `develop` branch hope it does not bother your rebasing

**Comment by JChanceHud** [comment]
It's cool, just please no big refactors ;-)
