### ISSUE TITLE
Error with event listeners

### ISSUE THREAD

**Issue by JChanceHud** [zkopru-network/zkopru#330]
When there are lots of events to ingest the event listeners tend to error:
```
[1638847792344] INFO (1 on bd32a5782310): core/synchronizer - Deposit Event Error occured
/src/node_modules/web3-providers-ws/node_modules/web3-core-helpers/src/errors.js:69
        return new Error('CONNECTION ERROR: Provider started to reconnect before the response got received!');
               ^

Error: CONNECTION ERROR: Provider started to reconnect before the response got received!
    at Object.PendingRequestsOnReconnectingError (/src/node_modules/web3-providers-ws/node_modules/web3-core-helpers/src/errors.js:69:16)
    at /src/node_modules/web3-providers-ws/src/index.js:395:37
    at Map.forEach (<anonymous>)
    at WebsocketProvider.reconnect (/src/node_modules/web3-providers-ws/src/index.js:394:28)
    at WebsocketProvider._onClose (/src/node_modules/web3-providers-ws/src/index.js:174:14)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/src/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onClose (/src/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/src/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (node:events:390:28)
    at WebSocketConnection.drop (/src/node_modules/websocket/lib/WebSocketConnection.js:475:14)
    at /src/node_modules/websocket/lib/WebSocketConnection.js:303:18
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

```

**Comment by JChanceHud** [comment]
The deposit event listener has completely failed after a few thousand deposits. Going to rewrite our data ingestion system to request chunks of data up to a pivot point.
