### ISSUE TITLE
Validator error handling

### ISSUE THREAD

**Issue by sifnoc** [zkopru-network/zkopru#374]
The validator got this error when the coordinator processing proposals after the 8th slash event.

```
[1645232606223] INFO (1 on 3185da9aa28c): core/block-processor - Processing proposal #955()
[1645232606900] INFO (1 on 3185da9aa28c): core/snark-verifier.ts - verifyTx(0xd29d841dd7f0817c29641204c0cfcfaab716f79796785975d56f37abfe46f0c5) => true
[1645232606901] WARN (1 on 3185da9aa28c): core/fullnode-validator - offchain validation failed: An inflow is referencing an invalid UTXO root.                                               
[1645232606952] WARN (1 on 3185da9aa28c): core/block-processor - challenge: undefined      
[1645232606952] INFO (1 on 3185da9aa28c): core/zkopru-node - Found a slashable proposal. Didn't execute the slash tx.
[1645232607001] INFO (1 on 3185da9aa28c): core/block-processor - Processing proposal #956()
AssertionError [ERR_ASSERTION]: Nullifier tree root mismatch
    at FullValidator.<anonymous> (/src/packages/core/dist/validator/validator.js:103:29)
    at Generator.next (<anonymous>)
    at fulfilled (/src/packages/core/dist/validator/validator.js:5:58) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='                                                                                                                                                                              
}
```

**Comment by sifnoc** [comment]
This issue fixed with https://github.com/zkopru-network/zkopru/tree/sync-fix
Good job! @vimwitch
